name: "Flutter Analyze Commenter"
description: "Auto comment on PRs based on Flutter Analyze results"
author: "yorifuji"
branding:
  icon: "code"
  color: "blue"
inputs:
  analyze_log:
    description: "Path to the Flutter analyze log file"
    required: true
  verbose:
    description: "Enable verbose logging"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Comment on PR based on Flutter Analyze results
      uses: actions/github-script@v6
      env:
        ANALYZE_LOG: ${{ inputs.analyze_log }}
        VERBOSE: ${{ inputs.verbose }}
      with:
        script: |
          const analyzeLog = process.env.ANALYZE_LOG;
          const verboseLogging = process.env.VERBOSE === 'true';
          const workingDir = process.env.GITHUB_WORKSPACE; // /home/runner/...
          const maxIssues = parseInt(process.env.MAX_ISSUES, 10) || 10;
          const perPage = parseInt(process.env.PER_PAGE, 10) || 100;
          const script = require("${{github.action_path}}/index.js")
          script({ core, github, context, analyzeLog, verboseLogging, workingDir, maxIssues, perPage })
